---
:orientdb:
 :server: 172.28.50.25 # localhost # 172.28.50.109 # localhost   #mailout.halfgarten-capital.de
 :port: 2480
 :logger: stdout           # 'file' or 'stdout'
 :database: 
   :development: GratefulDeadConcerts
   :production: hcn_data
   :test:  temp
 :admin:
   :user: hctw
   :pass: hc
 :auth:
   :user: topo
   :pass: focus

# hfx: 101
